from app.database import Base, SessionLocal, engine
from app.models import Category, Product


PRODUCTS = [
    {
        "name": "Notebook Pro 14",
        "category": "Eletronicos",
        "description": "Notebook ultrafino com tela Full HD e bateria para longas jornadas.",
        "price": 2499.90,
        "stock": 12,
        "image_url": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Fone Bluetooth X9",
        "category": "Audio",
        "description": "Fones com cancelamento de ruido e audio imersivo para musica e chamadas.",
        "price": 399.99,
        "stock": 28,
        "image_url": "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Smartwatch Active",
        "category": "Acessorios",
        "description": "Relogio inteligente com monitoramento de saude e notificacoes.",
        "price": 799.00,
        "stock": 18,
        "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Camera Mirrorless",
        "category": "Fotografia",
        "description": "Camera leve com foco rapido, gravacao 4K e alta qualidade de imagem.",
        "price": 1899.00,
        "stock": 9,
        "image_url": "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Mesa de Escritorio",
        "category": "Casa",
        "description": "Mesa moderna com acabamento premium, ideal para home office.",
        "price": 679.90,
        "stock": 7,
        "image_url": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Cafeteira Premium",
        "category": "Casa",
        "description": "Cafeteira com preparo rapido e design sofisticado para o dia a dia.",
        "price": 449.90,
        "stock": 15,
        "image_url": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Monitor UltraWide 34",
        "category": "Eletronicos",
        "description": "Monitor ultrawide para produtividade, criacao e entretenimento com mais espaco na tela.",
        "price": 1299.90,
        "stock": 10,
        "image_url": "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Teclado Mecanico RGB",
        "category": "Acessorios",
        "description": "Teclado mecanico compacto com iluminacao RGB e resposta precisa.",
        "price": 249.90,
        "stock": 22,
        "image_url": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Poltrona Conforto",
        "category": "Casa",
        "description": "Poltrona confortavel com design contemporaneo para seu espaco de descanso.",
        "price": 899.90,
        "stock": 6,
        "image_url": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Caixa de Som Portatil",
        "category": "Audio",
        "description": "Caixa de som portatil com graves fortes, bateria duradoura e conexao sem fio.",
        "price": 179.90,
        "stock": 31,
        "image_url": "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Tablet Vision 11",
        "category": "Eletronicos",
        "description": "Tablet leve com tela de alta definicao, desempenho fluido e bateria para o dia inteiro.",
        "price": 1199.90,
        "stock": 14,
        "image_url": "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Luminaria de Mesa LED",
        "category": "Casa",
        "description": "Luminaria articulada com luz regulavel para deixar seu espaco de trabalho mais confortavel.",
        "price": 129.90,
        "stock": 24,
        "image_url": "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Mouse Sem Fio Precision",
        "category": "Acessorios",
        "description": "Mouse ergonomico sem fio com sensor preciso e bateria de longa duracao.",
        "price": 159.90,
        "stock": 35,
        "image_url": "https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Microfone Studio USB",
        "category": "Audio",
        "description": "Microfone USB com captacao nitida para reunioes, podcasts e criacao de conteudo.",
        "price": 329.90,
        "stock": 11,
        "image_url": "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Notebook Air 13",
        "category": "Eletronicos",
        "description": "Notebook leve com acabamento premium, desempenho rapido e tela de alta resolucao.",
        "price": 3299.90,
        "stock": 8,
        "image_url": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Smart TV 55 4K",
        "category": "Eletronicos",
        "description": "Smart TV 4K com cores vibrantes, sistema inteligente e conexao para seus aplicativos.",
        "price": 2399.90,
        "stock": 5,
        "image_url": "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Console Game Pro",
        "category": "Eletronicos",
        "description": "Console de ultima geracao para jogar com graficos imersivos e carregamento rapido.",
        "price": 2799.90,
        "stock": 7,
        "image_url": "https://images.unsplash.com/photo-1605901309584-818e25960a8f?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Leitor Digital Ink",
        "category": "Eletronicos",
        "description": "Leitor digital compacto com tela confortavel para longas sessoes de leitura.",
        "price": 599.90,
        "stock": 16,
        "image_url": "https://images.unsplash.com/photo-1592496001020-d31bd830651f?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Projetor Cinema HD",
        "category": "Eletronicos",
        "description": "Projetor portatil para transformar qualquer ambiente em uma sala de cinema.",
        "price": 899.90,
        "stock": 10,
        "image_url": "https://images.unsplash.com/photo-1535016120720-40c646be5580?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Hub USB-C Pro",
        "category": "Eletronicos",
        "description": "Hub USB-C com multiplas portas para conectar perifericos e expandir seu setup.",
        "price": 189.90,
        "stock": 26,
        "image_url": "https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Carregador Wireless Duo",
        "category": "Eletronicos",
        "description": "Base de carregamento sem fio para recarregar dois dispositivos simultaneamente.",
        "price": 219.90,
        "stock": 30,
        "image_url": "https://images.unsplash.com/photo-1586953208448-b95a79798f07?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Fone In-Ear Sport",
        "category": "Audio",
        "description": "Fone esportivo leve com encaixe seguro e resistencia para sua rotina de exercicios.",
        "price": 149.90,
        "stock": 32,
        "image_url": "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Headset Gamer 7.1",
        "category": "Audio",
        "description": "Headset gamer com som surround, microfone ajustavel e conforto para longas partidas.",
        "price": 289.90,
        "stock": 19,
        "image_url": "https://images.unsplash.com/photo-1599669454699-248893623440?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Soundbar Compact",
        "category": "Audio",
        "description": "Soundbar compacta para melhorar o audio da TV com graves equilibrados e Bluetooth.",
        "price": 549.90,
        "stock": 12,
        "image_url": "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Toca-Discos Vintage",
        "category": "Audio",
        "description": "Toca-discos com visual classico, alto-falantes integrados e conexao para dispositivos.",
        "price": 699.90,
        "stock": 6,
        "image_url": "https://images.unsplash.com/photo-1461360228754-6e81c478b882?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Gravador de Voz Pocket",
        "category": "Audio",
        "description": "Gravador compacto para entrevistas, aulas e anotacoes com audio nitido.",
        "price": 199.90,
        "stock": 21,
        "image_url": "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Amplificador Bluetooth",
        "category": "Audio",
        "description": "Amplificador versatil para conectar suas caixas e ouvir musica com mais potencia.",
        "price": 459.90,
        "stock": 9,
        "image_url": "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Fone com Fio Studio",
        "category": "Audio",
        "description": "Fone fechado com resposta detalhada para producao musical e escuta diaria.",
        "price": 229.90,
        "stock": 17,
        "image_url": "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Teclado Slim Sem Fio",
        "category": "Acessorios",
        "description": "Teclado sem fio fino e silencioso para trabalhar com mais conforto e organizacao.",
        "price": 179.90,
        "stock": 25,
        "image_url": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Webcam Full HD",
        "category": "Acessorios",
        "description": "Webcam Full HD com microfone integrado para reunioes e transmissoes profissionais.",
        "price": 219.90,
        "stock": 18,
        "image_url": "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Suporte Ergonomico para Notebook",
        "category": "Acessorios",
        "description": "Suporte ajustavel para elevar a tela e melhorar a postura durante o trabalho.",
        "price": 119.90,
        "stock": 40,
        "image_url": "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Mochila Tech Urban",
        "category": "Acessorios",
        "description": "Mochila resistente com compartimentos acolchoados para notebook e acessorios.",
        "price": 259.90,
        "stock": 13,
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Cabo USB-C Reforcado",
        "category": "Acessorios",
        "description": "Cabo USB-C duravel para carregamento rapido e transferencia segura de dados.",
        "price": 59.90,
        "stock": 60,
        "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Mouse Pad Desk XL",
        "category": "Acessorios",
        "description": "Mouse pad amplo com superficie precisa e base antiderrapante para seu setup.",
        "price": 89.90,
        "stock": 45,
        "image_url": "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Organizador de Cabos",
        "category": "Acessorios",
        "description": "Kit de organizadores para manter cabos e carregadores sempre no lugar.",
        "price": 39.90,
        "stock": 80,
        "image_url": "https://images.unsplash.com/photo-1586953208448-b95a79798f07?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Lente Prime 50mm",
        "category": "Fotografia",
        "description": "Lente prime luminosa para retratos com fundo desfocado e excelente nitidez.",
        "price": 1299.90,
        "stock": 5,
        "image_url": "https://images.unsplash.com/photo-1606986628253-9e3e3e1b1d68?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Tripe Profissional Carbono",
        "category": "Fotografia",
        "description": "Tripe leve e estavel com ajustes precisos para fotos e videos profissionais.",
        "price": 749.90,
        "stock": 8,
        "image_url": "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Flash Speedlight Pro",
        "category": "Fotografia",
        "description": "Flash externo com controle de potencia para iluminar retratos e eventos.",
        "price": 489.90,
        "stock": 11,
        "image_url": "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Mochila para Camera",
        "category": "Fotografia",
        "description": "Mochila acolchoada com divisoes ajustaveis para transportar camera e lentes.",
        "price": 329.90,
        "stock": 14,
        "image_url": "https://images.unsplash.com/photo-1491637639811-60e2756cc1c7?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Cartao SD 256GB Pro",
        "category": "Fotografia",
        "description": "Cartao de memoria veloz para gravacoes em alta resolucao e disparos continuos.",
        "price": 199.90,
        "stock": 28,
        "image_url": "https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Kit de Filtros Fotograficos",
        "category": "Fotografia",
        "description": "Kit com filtros essenciais para controlar luz e criar efeitos durante as fotos.",
        "price": 279.90,
        "stock": 10,
        "image_url": "https://images.unsplash.com/photo-1452780212940-6f5c0d14d848?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Bateria Extra Mirrorless",
        "category": "Fotografia",
        "description": "Bateria reserva para fotografar por mais tempo sem interromper sua sessao.",
        "price": 169.90,
        "stock": 18,
        "image_url": "https://images.unsplash.com/photo-1512790182412-b19e6d62bc39?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Luz LED para Video",
        "category": "Fotografia",
        "description": "Luz LED portatil com temperatura ajustavel para videos e retratos bem iluminados.",
        "price": 399.90,
        "stock": 9,
        "image_url": "https://images.unsplash.com/photo-1492619375914-88005aa9e8fb?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Fundo Fotografico Neutro",
        "category": "Fotografia",
        "description": "Fundo fotografico versatil para criar cenarios limpos em estudios e home studios.",
        "price": 149.90,
        "stock": 20,
        "image_url": "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Aspirador Robo Smart",
        "category": "Casa",
        "description": "Aspirador robo inteligente com mapeamento de ambientes e programacao pelo celular.",
        "price": 1199.90,
        "stock": 7,
        "image_url": "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Kit de Panelas Ceramic",
        "category": "Casa",
        "description": "Conjunto de panelas com revestimento ceramico e design para cozinhar todos os dias.",
        "price": 499.90,
        "stock": 12,
        "image_url": "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Jogo de Cama Premium",
        "category": "Casa",
        "description": "Jogo de cama macio com acabamento elegante para renovar o quarto.",
        "price": 289.90,
        "stock": 15,
        "image_url": "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Purificador de Ar",
        "category": "Casa",
        "description": "Purificador silencioso para deixar o ar do ambiente mais limpo e agradavel.",
        "price": 649.90,
        "stock": 10,
        "image_url": "https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Organizador Modular",
        "category": "Casa",
        "description": "Organizador modular para guardar objetos e aproveitar melhor os espacos da casa.",
        "price": 99.90,
        "stock": 36,
        "image_url": "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=900&q=80",
    },
    {
        "name": "Ventilador Torre Digital",
        "category": "Casa",
        "description": "Ventilador torre com painel digital, timer e tres velocidades para dias quentes.",
        "price": 379.90,
        "stock": 13,
        "image_url": "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=900&q=80",
    },
]


def seed_products():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    created = 0
    try:
        for product_data in PRODUCTS:
            category = db.query(Category).filter(Category.name == product_data["category"]).first()
            if not category:
                category = Category(name=product_data["category"])
                db.add(category)
                db.flush()

            existing_product = db.query(Product).filter(Product.name == product_data["name"]).first()
            if existing_product:
                continue

            db.add(
                Product(
                    name=product_data["name"],
                    description=product_data["description"],
                    price=product_data["price"],
                    stock=product_data["stock"],
                    image_url=product_data["image_url"],
                    category_id=category.id,
                    is_active=True,
                )
            )
            created += 1

        db.commit()
        print(f"Produtos criados: {created}")
    finally:
        db.close()


if __name__ == "__main__":
    seed_products()
